#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace travelH2tour.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;


	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name = "TravelTour")]
	public partial class dbTravelTourDataContext : System.Data.Linq.DataContext
	{

		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();

		#region Extensibility Method Definitions
		partial void OnCreated();
		partial void InsertADMIN(ADMIN instance);
		partial void UpdateADMIN(ADMIN instance);
		partial void DeleteADMIN(ADMIN instance);
		partial void InsertCT_DICHVU(CT_DICHVU instance);
		partial void UpdateCT_DICHVU(CT_DICHVU instance);
		partial void DeleteCT_DICHVU(CT_DICHVU instance);
		partial void InsertCT_TOUR(CT_TOUR instance);
		partial void UpdateCT_TOUR(CT_TOUR instance);
		partial void DeleteCT_TOUR(CT_TOUR instance);
		partial void InsertDIADIEM(DIADIEM instance);
		partial void UpdateDIADIEM(DIADIEM instance);
		partial void DeleteDIADIEM(DIADIEM instance);
		partial void InsertDICHVU(DICHVU instance);
		partial void UpdateDICHVU(DICHVU instance);
		partial void DeleteDICHVU(DICHVU instance);
		partial void InsertKHACHHANG(KHACHHANG instance);
		partial void UpdateKHACHHANG(KHACHHANG instance);
		partial void DeleteKHACHHANG(KHACHHANG instance);
		partial void InsertLOAITOUR(LOAITOUR instance);
		partial void UpdateLOAITOUR(LOAITOUR instance);
		partial void DeleteLOAITOUR(LOAITOUR instance);
		partial void InsertNHANVIEN(NHANVIEN instance);
		partial void UpdateNHANVIEN(NHANVIEN instance);
		partial void DeleteNHANVIEN(NHANVIEN instance);
		partial void InsertPHIEUDATTOUR(PHIEUDATTOUR instance);
		partial void UpdatePHIEUDATTOUR(PHIEUDATTOUR instance);
		partial void DeletePHIEUDATTOUR(PHIEUDATTOUR instance);
		partial void InsertTOURDL(TOURDL instance);
		partial void UpdateTOURDL(TOURDL instance);
		partial void DeleteTOURDL(TOURDL instance);
		#endregion

		public dbTravelTourDataContext(string connection) :
				base(connection, mappingSource)
		{
			OnCreated();
		}

		public dbTravelTourDataContext() :
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["TravelTourConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}

		public dbTravelTourDataContext(System.Data.IDbConnection connection) :
				base(connection, mappingSource)
		{
			OnCreated();
		}

		public dbTravelTourDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) :
				base(connection, mappingSource)
		{
			OnCreated();
		}

		public dbTravelTourDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) :
				base(connection, mappingSource)
		{
			OnCreated();
		}

		public System.Data.Linq.Table<ADMIN> ADMINs
		{
			get
			{
				return this.GetTable<ADMIN>();
			}
		}

		public System.Data.Linq.Table<CT_DICHVU> CT_DICHVUs
		{
			get
			{
				return this.GetTable<CT_DICHVU>();
			}
		}

		public System.Data.Linq.Table<CT_TOUR> CT_TOURs
		{
			get
			{
				return this.GetTable<CT_TOUR>();
			}
		}

		public System.Data.Linq.Table<DIADIEM> DIADIEMs
		{
			get
			{
				return this.GetTable<DIADIEM>();
			}
		}

		public System.Data.Linq.Table<DICHVU> DICHVUs
		{
			get
			{
				return this.GetTable<DICHVU>();
			}
		}

		public System.Data.Linq.Table<KHACHHANG> KHACHHANGs
		{
			get
			{
				return this.GetTable<KHACHHANG>();
			}
		}

		public System.Data.Linq.Table<LOAITOUR> LOAITOURs
		{
			get
			{
				return this.GetTable<LOAITOUR>();
			}
		}

		public System.Data.Linq.Table<NHANVIEN> NHANVIENs
		{
			get
			{
				return this.GetTable<NHANVIEN>();
			}
		}

		public System.Data.Linq.Table<PHIEUDATTOUR> PHIEUDATTOURs
		{
			get
			{
				return this.GetTable<PHIEUDATTOUR>();
			}
		}

		public System.Data.Linq.Table<TOURDL> TOURDLs
		{
			get
			{
				return this.GetTable<TOURDL>();
			}
		}
	}

	[global::System.Data.Linq.Mapping.TableAttribute(Name = "dbo.ADMIN")]
	public partial class ADMIN : INotifyPropertyChanging, INotifyPropertyChanged
	{

		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);

		private string _TAIKHOAN_ADMIN;

		private string _MATKHAU_ADMIN;

		#region Extensibility Method Definitions
		partial void OnLoaded();
		partial void OnValidate(System.Data.Linq.ChangeAction action);
		partial void OnCreated();
		partial void OnTAIKHOAN_ADMINChanging(string value);
		partial void OnTAIKHOAN_ADMINChanged();
		partial void OnMATKHAU_ADMINChanging(string value);
		partial void OnMATKHAU_ADMINChanged();
		#endregion

		public ADMIN()
		{
			OnCreated();
		}

		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_TAIKHOAN_ADMIN", DbType = "VarChar(100) NOT NULL", CanBeNull = false, IsPrimaryKey = true)]
		public string TAIKHOAN_ADMIN
		{
			get
			{
				return this._TAIKHOAN_ADMIN;
			}
			set
			{
				if ((this._TAIKHOAN_ADMIN != value))
				{
					this.OnTAIKHOAN_ADMINChanging(value);
					this.SendPropertyChanging();
					this._TAIKHOAN_ADMIN = value;
					this.SendPropertyChanged("TAIKHOAN_ADMIN");
					this.OnTAIKHOAN_ADMINChanged();
				}
			}
		}

		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_MATKHAU_ADMIN", DbType = "VarChar(100)")]
		public string MATKHAU_ADMIN
		{
			get
			{
				return this._MATKHAU_ADMIN;
			}
			set
			{
				if ((this._MATKHAU_ADMIN != value))
				{
					this.OnMATKHAU_ADMINChanging(value);
					this.SendPropertyChanging();
					this._MATKHAU_ADMIN = value;
					this.SendPropertyChanged("MATKHAU_ADMIN");
					this.OnMATKHAU_ADMINChanged();
				}
			}
		}

		public event PropertyChangingEventHandler PropertyChanging;

		public event PropertyChangedEventHandler PropertyChanged;

		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}

		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}

	[global::System.Data.Linq.Mapping.TableAttribute(Name = "dbo.CT_DICHVU")]
	public partial class CT_DICHVU : INotifyPropertyChanging, INotifyPropertyChanged
	{

		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);

		private long _MAPDT;

		private long _MADV;

		private EntityRef<DICHVU> _DICHVU;

		private EntityRef<DICHVU> _DICHVU1;

		private EntityRef<DICHVU> _DICHVU2;

		private EntityRef<PHIEUDATTOUR> _PHIEUDATTOUR;

		private EntityRef<PHIEUDATTOUR> _PHIEUDATTOUR1;

		#region Extensibility Method Definitions
		partial void OnLoaded();
		partial void OnValidate(System.Data.Linq.ChangeAction action);
		partial void OnCreated();
		partial void OnMAPDTChanging(long value);
		partial void OnMAPDTChanged();
		partial void OnMADVChanging(long value);
		partial void OnMADVChanged();
		#endregion

		public CT_DICHVU()
		{
			this._DICHVU = default(EntityRef<DICHVU>);
			this._DICHVU1 = default(EntityRef<DICHVU>);
			this._DICHVU2 = default(EntityRef<DICHVU>);
			this._PHIEUDATTOUR = default(EntityRef<PHIEUDATTOUR>);
			this._PHIEUDATTOUR1 = default(EntityRef<PHIEUDATTOUR>);
			OnCreated();
		}

		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_MAPDT", DbType = "BigInt NOT NULL", IsPrimaryKey = true)]
		public long MAPDT
		{
			get
			{
				return this._MAPDT;
			}
			set
			{
				if ((this._MAPDT != value))
				{
					if ((this._PHIEUDATTOUR.HasLoadedOrAssignedValue || this._PHIEUDATTOUR1.HasLoadedOrAssignedValue))
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMAPDTChanging(value);
					this.SendPropertyChanging();
					this._MAPDT = value;
					this.SendPropertyChanged("MAPDT");
					this.OnMAPDTChanged();
				}
			}
		}

		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_MADV", DbType = "BigInt NOT NULL", IsPrimaryKey = true)]
		public long MADV
		{
			get
			{
				return this._MADV;
			}
			set
			{
				if ((this._MADV != value))
				{
					if (((this._DICHVU.HasLoadedOrAssignedValue || this._DICHVU1.HasLoadedOrAssignedValue)
								|| this._DICHVU2.HasLoadedOrAssignedValue))
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMADVChanging(value);
					this.SendPropertyChanging();
					this._MADV = value;
					this.SendPropertyChanged("MADV");
					this.OnMADVChanged();
				}
			}
		}

		[global::System.Data.Linq.Mapping.AssociationAttribute(Name = "DICHVU_CT_DICHVU", Storage = "_DICHVU", ThisKey = "MADV", OtherKey = "MADV", IsForeignKey = true)]
		public DICHVU DICHVU
		{
			get
			{
				return this._DICHVU.Entity;
			}
			set
			{
				DICHVU previousValue = this._DICHVU.Entity;
				if (((previousValue != value)
							|| (this._DICHVU.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._DICHVU.Entity = null;
						previousValue.CT_DICHVUs.Remove(this);
					}
					this._DICHVU.Entity = value;
					if ((value != null))
					{
						value.CT_DICHVUs.Add(this);
						this._MADV = value.MADV;
					}
					else
					{
						this._MADV = default(long);
					}
					this.SendPropertyChanged("DICHVU");
				}
			}
		}

		[global::System.Data.Linq.Mapping.AssociationAttribute(Name = "DICHVU_CT_DICHVU1", Storage = "_DICHVU1", ThisKey = "MADV", OtherKey = "MADV", IsForeignKey = true)]
		public DICHVU DICHVU1
		{
			get
			{
				return this._DICHVU1.Entity;
			}
			set
			{
				DICHVU previousValue = this._DICHVU1.Entity;
				if (((previousValue != value)
							|| (this._DICHVU1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._DICHVU1.Entity = null;
						previousValue.CT_DICHVUs1.Remove(this);
					}
					this._DICHVU1.Entity = value;
					if ((value != null))
					{
						value.CT_DICHVUs1.Add(this);
						this._MADV = value.MADV;
					}
					else
					{
						this._MADV = default(long);
					}
					this.SendPropertyChanged("DICHVU1");
				}
			}
		}

		[global::System.Data.Linq.Mapping.AssociationAttribute(Name = "DICHVU_CT_DICHVU2", Storage = "_DICHVU2", ThisKey = "MADV", OtherKey = "MADV", IsForeignKey = true)]
		public DICHVU DICHVU2
		{
			get
			{
				return this._DICHVU2.Entity;
			}
			set
			{
				DICHVU previousValue = this._DICHVU2.Entity;
				if (((previousValue != value)
							|| (this._DICHVU2.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._DICHVU2.Entity = null;
						previousValue.CT_DICHVUs2.Remove(this);
					}
					this._DICHVU2.Entity = value;
					if ((value != null))
					{
						value.CT_DICHVUs2.Add(this);
						this._MADV = value.MADV;
					}
					else
					{
						this._MADV = default(long);
					}
					this.SendPropertyChanged("DICHVU2");
				}
			}
		}

		[global::System.Data.Linq.Mapping.AssociationAttribute(Name = "PHIEUDATTOUR_CT_DICHVU", Storage = "_PHIEUDATTOUR", ThisKey = "MAPDT", OtherKey = "MAPDT", IsForeignKey = true)]
		public PHIEUDATTOUR PHIEUDATTOUR
		{
			get
			{
				return this._PHIEUDATTOUR.Entity;
			}
			set
			{
				PHIEUDATTOUR previousValue = this._PHIEUDATTOUR.Entity;
				if (((previousValue != value)
							|| (this._PHIEUDATTOUR.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._PHIEUDATTOUR.Entity = null;
						previousValue.CT_DICHVUs.Remove(this);
					}
					this._PHIEUDATTOUR.Entity = value;
					if ((value != null))
					{
						value.CT_DICHVUs.Add(this);
						this._MAPDT = value.MAPDT;
					}
					else
					{
						this._MAPDT = default(long);
					}
					this.SendPropertyChanged("PHIEUDATTOUR");
				}
			}
		}

		[global::System.Data.Linq.Mapping.AssociationAttribute(Name = "PHIEUDATTOUR_CT_DICHVU1", Storage = "_PHIEUDATTOUR1", ThisKey = "MAPDT", OtherKey = "MAPDT", IsForeignKey = true)]
		public PHIEUDATTOUR PHIEUDATTOUR1
		{
			get
			{
				return this._PHIEUDATTOUR1.Entity;
			}
			set
			{
				PHIEUDATTOUR previousValue = this._PHIEUDATTOUR1.Entity;
				if (((previousValue != value)
							|| (this._PHIEUDATTOUR1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._PHIEUDATTOUR1.Entity = null;
						previousValue.CT_DICHVUs1.Remove(this);
					}
					this._PHIEUDATTOUR1.Entity = value;
					if ((value != null))
					{
						value.CT_DICHVUs1.Add(this);
						this._MAPDT = value.MAPDT;
					}
					else
					{
						this._MAPDT = default(long);
					}
					this.SendPropertyChanged("PHIEUDATTOUR1");
				}
			}
		}

		public event PropertyChangingEventHandler PropertyChanging;

		public event PropertyChangedEventHandler PropertyChanged;

		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}

		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}

	[global::System.Data.Linq.Mapping.TableAttribute(Name = "dbo.CT_TOUR")]
	public partial class CT_TOUR : INotifyPropertyChanging, INotifyPropertyChanged
	{

		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);

		private long _MAPDT;

		private long _MATOUR;

		private System.Nullable<System.DateTime> _NGAYDI;

		private System.Nullable<System.DateTime> _NGAYVE;

		private System.Nullable<int> _SOLUONGKHACH;

		private string _DANHGIATUKHACHHANG;

		private EntityRef<PHIEUDATTOUR> _PHIEUDATTOUR;

		private EntityRef<PHIEUDATTOUR> _PHIEUDATTOUR1;

		private EntityRef<PHIEUDATTOUR> _PHIEUDATTOUR2;

		private EntityRef<TOURDL> _TOURDL;

		private EntityRef<TOURDL> _TOURDL1;

		private EntityRef<TOURDL> _TOURDL2;

		#region Extensibility Method Definitions
		partial void OnLoaded();
		partial void OnValidate(System.Data.Linq.ChangeAction action);
		partial void OnCreated();
		partial void OnMAPDTChanging(long value);
		partial void OnMAPDTChanged();
		partial void OnMATOURChanging(long value);
		partial void OnMATOURChanged();
		partial void OnNGAYDIChanging(System.Nullable<System.DateTime> value);
		partial void OnNGAYDIChanged();
		partial void OnNGAYVEChanging(System.Nullable<System.DateTime> value);
		partial void OnNGAYVEChanged();
		partial void OnSOLUONGKHACHChanging(System.Nullable<int> value);
		partial void OnSOLUONGKHACHChanged();
		partial void OnDANHGIATUKHACHHANGChanging(string value);
		partial void OnDANHGIATUKHACHHANGChanged();
		#endregion

		public CT_TOUR()
		{
			this._PHIEUDATTOUR = default(EntityRef<PHIEUDATTOUR>);
			this._PHIEUDATTOUR1 = default(EntityRef<PHIEUDATTOUR>);
			this._PHIEUDATTOUR2 = default(EntityRef<PHIEUDATTOUR>);
			this._TOURDL = default(EntityRef<TOURDL>);
			this._TOURDL1 = default(EntityRef<TOURDL>);
			this._TOURDL2 = default(EntityRef<TOURDL>);
			OnCreated();
		}

		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_MAPDT", DbType = "BigInt NOT NULL", IsPrimaryKey = true)]
		public long MAPDT
		{
			get
			{
				return this._MAPDT;
			}
			set
			{
				if ((this._MAPDT != value))
				{
					if (((this._PHIEUDATTOUR.HasLoadedOrAssignedValue || this._PHIEUDATTOUR1.HasLoadedOrAssignedValue)
								|| this._PHIEUDATTOUR2.HasLoadedOrAssignedValue))
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMAPDTChanging(value);
					this.SendPropertyChanging();
					this._MAPDT = value;
					this.SendPropertyChanged("MAPDT");
					this.OnMAPDTChanged();
				}
			}
		}

		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_MATOUR", DbType = "BigInt NOT NULL", IsPrimaryKey = true)]
		public long MATOUR
		{
			get
			{
				return this._MATOUR;
			}
			set
			{
				if ((this._MATOUR != value))
				{
					if (((this._TOURDL.HasLoadedOrAssignedValue || this._TOURDL1.HasLoadedOrAssignedValue)
								|| this._TOURDL2.HasLoadedOrAssignedValue))
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMATOURChanging(value);
					this.SendPropertyChanging();
					this._MATOUR = value;
					this.SendPropertyChanged("MATOUR");
					this.OnMATOURChanged();
				}
			}
		}

		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_NGAYDI", DbType = "DateTime")]
		public System.Nullable<System.DateTime> NGAYDI
		{
			get
			{
				return this._NGAYDI;
			}
			set
			{
				if ((this._NGAYDI != value))
				{
					this.OnNGAYDIChanging(value);
					this.SendPropertyChanging();
					this._NGAYDI = value;
					this.SendPropertyChanged("NGAYDI");
					this.OnNGAYDIChanged();
				}
			}
		}

		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_NGAYVE", DbType = "DateTime")]
		public System.Nullable<System.DateTime> NGAYVE
		{
			get
			{
				return this._NGAYVE;
			}
			set
			{
				if ((this._NGAYVE != value))
				{
					this.OnNGAYVEChanging(value);
					this.SendPropertyChanging();
					this._NGAYVE = value;
					this.SendPropertyChanged("NGAYVE");
					this.OnNGAYVEChanged();
				}
			}
		}

		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_SOLUONGKHACH", DbType = "Int")]
		public System.Nullable<int> SOLUONGKHACH
		{
			get
			{
				return this._SOLUONGKHACH;
			}
			set
			{
				if ((this._SOLUONGKHACH != value))
				{
					this.OnSOLUONGKHACHChanging(value);
					this.SendPropertyChanging();
					this._SOLUONGKHACH = value;
					this.SendPropertyChanged("SOLUONGKHACH");
					this.OnSOLUONGKHACHChanged();
				}
			}
		}

		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_DANHGIATUKHACHHANG", DbType = "NVarChar(2000)")]
		public string DANHGIATUKHACHHANG
		{
			get
			{
				return this._DANHGIATUKHACHHANG;
			}
			set
			{
				if ((this._DANHGIATUKHACHHANG != value))
				{
					this.OnDANHGIATUKHACHHANGChanging(value);
					this.SendPropertyChanging();
					this._DANHGIATUKHACHHANG = value;
					this.SendPropertyChanged("DANHGIATUKHACHHANG");
					this.OnDANHGIATUKHACHHANGChanged();
				}
			}
		}

		[global::System.Data.Linq.Mapping.AssociationAttribute(Name = "PHIEUDATTOUR_CT_TOUR", Storage = "_PHIEUDATTOUR", ThisKey = "MAPDT", OtherKey = "MAPDT", IsForeignKey = true)]
		public PHIEUDATTOUR PHIEUDATTOUR
		{
			get
			{
				return this._PHIEUDATTOUR.Entity;
			}
			set
			{
				PHIEUDATTOUR previousValue = this._PHIEUDATTOUR.Entity;
				if (((previousValue != value)
							|| (this._PHIEUDATTOUR.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._PHIEUDATTOUR.Entity = null;
						previousValue.CT_TOURs.Remove(this);
					}
					this._PHIEUDATTOUR.Entity = value;
					if ((value != null))
					{
						value.CT_TOURs.Add(this);
						this._MAPDT = value.MAPDT;
					}
					else
					{
						this._MAPDT = default(long);
					}
					this.SendPropertyChanged("PHIEUDATTOUR");
				}
			}
		}

		[global::System.Data.Linq.Mapping.AssociationAttribute(Name = "PHIEUDATTOUR_CT_TOUR1", Storage = "_PHIEUDATTOUR1", ThisKey = "MAPDT", OtherKey = "MAPDT", IsForeignKey = true)]
		public PHIEUDATTOUR PHIEUDATTOUR1
		{
			get
			{
				return this._PHIEUDATTOUR1.Entity;
			}
			set
			{
				PHIEUDATTOUR previousValue = this._PHIEUDATTOUR1.Entity;
				if (((previousValue != value)
							|| (this._PHIEUDATTOUR1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._PHIEUDATTOUR1.Entity = null;
						previousValue.CT_TOURs1.Remove(this);
					}
					this._PHIEUDATTOUR1.Entity = value;
					if ((value != null))
					{
						value.CT_TOURs1.Add(this);
						this._MAPDT = value.MAPDT;
					}
					else
					{
						this._MAPDT = default(long);
					}
					this.SendPropertyChanged("PHIEUDATTOUR1");
				}
			}
		}

		[global::System.Data.Linq.Mapping.AssociationAttribute(Name = "PHIEUDATTOUR_CT_TOUR2", Storage = "_PHIEUDATTOUR2", ThisKey = "MAPDT", OtherKey = "MAPDT", IsForeignKey = true)]
		public PHIEUDATTOUR PHIEUDATTOUR2
		{
			get
			{
				return this._PHIEUDATTOUR2.Entity;
			}
			set
			{
				PHIEUDATTOUR previousValue = this._PHIEUDATTOUR2.Entity;
				if (((previousValue != value)
							|| (this._PHIEUDATTOUR2.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._PHIEUDATTOUR2.Entity = null;
						previousValue.CT_TOURs2.Remove(this);
					}
					this._PHIEUDATTOUR2.Entity = value;
					if ((value != null))
					{
						value.CT_TOURs2.Add(this);
						this._MAPDT = value.MAPDT;
					}
					else
					{
						this._MAPDT = default(long);
					}
					this.SendPropertyChanged("PHIEUDATTOUR2");
				}
			}
		}

		[global::System.Data.Linq.Mapping.AssociationAttribute(Name = "TOURDL_CT_TOUR", Storage = "_TOURDL", ThisKey = "MATOUR", OtherKey = "MATOUR", IsForeignKey = true)]
		public TOURDL TOURDL
		{
			get
			{
				return this._TOURDL.Entity;
			}
			set
			{
				TOURDL previousValue = this._TOURDL.Entity;
				if (((previousValue != value)
							|| (this._TOURDL.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TOURDL.Entity = null;
						previousValue.CT_TOURs.Remove(this);
					}
					this._TOURDL.Entity = value;
					if ((value != null))
					{
						value.CT_TOURs.Add(this);
						this._MATOUR = value.MATOUR;
					}
					else
					{
						this._MATOUR = default(long);
					}
					this.SendPropertyChanged("TOURDL");
				}
			}
		}

		[global::System.Data.Linq.Mapping.AssociationAttribute(Name = "TOURDL_CT_TOUR1", Storage = "_TOURDL1", ThisKey = "MATOUR", OtherKey = "MATOUR", IsForeignKey = true)]
		public TOURDL TOURDL1
		{
			get
			{
				return this._TOURDL1.Entity;
			}
			set
			{
				TOURDL previousValue = this._TOURDL1.Entity;
				if (((previousValue != value)
							|| (this._TOURDL1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TOURDL1.Entity = null;
						previousValue.CT_TOURs1.Remove(this);
					}
					this._TOURDL1.Entity = value;
					if ((value != null))
					{
						value.CT_TOURs1.Add(this);
						this._MATOUR = value.MATOUR;
					}
					else
					{
						this._MATOUR = default(long);
					}
					this.SendPropertyChanged("TOURDL1");
				}
			}
		}

		[global::System.Data.Linq.Mapping.AssociationAttribute(Name = "TOURDL_CT_TOUR2", Storage = "_TOURDL2", ThisKey = "MATOUR", OtherKey = "MATOUR", IsForeignKey = true)]
		public TOURDL TOURDL2
		{
			get
			{
				return this._TOURDL2.Entity;
			}
			set
			{
				TOURDL previousValue = this._TOURDL2.Entity;
				if (((previousValue != value)
							|| (this._TOURDL2.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TOURDL2.Entity = null;
						previousValue.CT_TOURs2.Remove(this);
					}
					this._TOURDL2.Entity = value;
					if ((value != null))
					{
						value.CT_TOURs2.Add(this);
						this._MATOUR = value.MATOUR;
					}
					else
					{
						this._MATOUR = default(long);
					}
					this.SendPropertyChanged("TOURDL2");
				}
			}
		}

		public event PropertyChangingEventHandler PropertyChanging;

		public event PropertyChangedEventHandler PropertyChanged;

		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}

		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}

	[global::System.Data.Linq.Mapping.TableAttribute(Name = "dbo.DIADIEM")]
	public partial class DIADIEM : INotifyPropertyChanging, INotifyPropertyChanged
	{

		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);

		private long _MADIADIEM;

		private string _TENDIADIEM;

		private string _HINHDIADIEM;

		private EntitySet<TOURDL> _TOURDLs;

		private EntitySet<TOURDL> _TOURDLs1;

		private EntitySet<TOURDL> _TOURDLs2;

		#region Extensibility Method Definitions
		partial void OnLoaded();
		partial void OnValidate(System.Data.Linq.ChangeAction action);
		partial void OnCreated();
		partial void OnMADIADIEMChanging(long value);
		partial void OnMADIADIEMChanged();
		partial void OnTENDIADIEMChanging(string value);
		partial void OnTENDIADIEMChanged();
		partial void OnHINHDIADIEMChanging(string value);
		partial void OnHINHDIADIEMChanged();
		#endregion

		public DIADIEM()
		{
			this._TOURDLs = new EntitySet<TOURDL>(new Action<TOURDL>(this.attach_TOURDLs), new Action<TOURDL>(this.detach_TOURDLs));
			this._TOURDLs1 = new EntitySet<TOURDL>(new Action<TOURDL>(this.attach_TOURDLs1), new Action<TOURDL>(this.detach_TOURDLs1));
			this._TOURDLs2 = new EntitySet<TOURDL>(new Action<TOURDL>(this.attach_TOURDLs2), new Action<TOURDL>(this.detach_TOURDLs2));
			OnCreated();
		}

		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_MADIADIEM", AutoSync = AutoSync.OnInsert, DbType = "BigInt NOT NULL IDENTITY", IsPrimaryKey = true, IsDbGenerated = true)]
		public long MADIADIEM
		{
			get
			{
				return this._MADIADIEM;
			}
			set
			{
				if ((this._MADIADIEM != value))
				{
					this.OnMADIADIEMChanging(value);
					this.SendPropertyChanging();
					this._MADIADIEM = value;
					this.SendPropertyChanged("MADIADIEM");
					this.OnMADIADIEMChanged();
				}
			}
		}

		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_TENDIADIEM", DbType = "NVarChar(100)")]
		public string TENDIADIEM
		{
			get
			{
				return this._TENDIADIEM;
			}
			set
			{
				if ((this._TENDIADIEM != value))
				{
					this.OnTENDIADIEMChanging(value);
					this.SendPropertyChanging();
					this._TENDIADIEM = value;
					this.SendPropertyChanged("TENDIADIEM");
					this.OnTENDIADIEMChanged();
				}
			}
		}

		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_HINHDIADIEM", DbType = "VarChar(100)")]
		public string HINHDIADIEM
		{
			get
			{
				return this._HINHDIADIEM;
			}
			set
			{
				if ((this._HINHDIADIEM != value))
				{
					this.OnHINHDIADIEMChanging(value);
					this.SendPropertyChanging();
					this._HINHDIADIEM = value;
					this.SendPropertyChanged("HINHDIADIEM");
					this.OnHINHDIADIEMChanged();
				}
			}
		}

		[global::System.Data.Linq.Mapping.AssociationAttribute(Name = "DIADIEM_TOURDL", Storage = "_TOURDLs", ThisKey = "MADIADIEM", OtherKey = "MADIADIEM")]
		public EntitySet<TOURDL> TOURDLs
		{
			get
			{
				return this._TOURDLs;
			}
			set
			{
				this._TOURDLs.Assign(value);
			}
		}

		[global::System.Data.Linq.Mapping.AssociationAttribute(Name = "DIADIEM_TOURDL1", Storage = "_TOURDLs1", ThisKey = "MADIADIEM", OtherKey = "MADIADIEM")]
		public EntitySet<TOURDL> TOURDLs1
		{
			get
			{
				return this._TOURDLs1;
			}
			set
			{
				this._TOURDLs1.Assign(value);
			}
		}

		[global::System.Data.Linq.Mapping.AssociationAttribute(Name = "DIADIEM_TOURDL2", Storage = "_TOURDLs2", ThisKey = "MADIADIEM", OtherKey = "MADIADIEM")]
		public EntitySet<TOURDL> TOURDLs2
		{
			get
			{
				return this._TOURDLs2;
			}
			set
			{
				this._TOURDLs2.Assign(value);
			}
		}

		public event PropertyChangingEventHandler PropertyChanging;

		public event PropertyChangedEventHandler PropertyChanged;

		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}

		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}

		private void attach_TOURDLs(TOURDL entity)
		{
			this.SendPropertyChanging();
			entity.DIADIEM = this;
		}

		private void detach_TOURDLs(TOURDL entity)
		{
			this.SendPropertyChanging();
			entity.DIADIEM = null;
		}

		private void attach_TOURDLs1(TOURDL entity)
		{
			this.SendPropertyChanging();
			entity.DIADIEM1 = this;
		}

		private void detach_TOURDLs1(TOURDL entity)
		{
			this.SendPropertyChanging();
			entity.DIADIEM1 = null;
		}

		private void attach_TOURDLs2(TOURDL entity)
		{
			this.SendPropertyChanging();
			entity.DIADIEM2 = this;
		}

		private void detach_TOURDLs2(TOURDL entity)
		{
			this.SendPropertyChanging();
			entity.DIADIEM2 = null;
		}
	}

	[global::System.Data.Linq.Mapping.TableAttribute(Name = "dbo.DICHVU")]
	public partial class DICHVU : INotifyPropertyChanging, INotifyPropertyChanged
	{

		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);

		private long _MADV;

		private string _TENDV;

		private System.Nullable<decimal> _GIADV;

		private EntitySet<CT_DICHVU> _CT_DICHVUs;

		private EntitySet<CT_DICHVU> _CT_DICHVUs1;

		private EntitySet<CT_DICHVU> _CT_DICHVUs2;

		#region Extensibility Method Definitions
		partial void OnLoaded();
		partial void OnValidate(System.Data.Linq.ChangeAction action);
		partial void OnCreated();
		partial void OnMADVChanging(long value);
		partial void OnMADVChanged();
		partial void OnTENDVChanging(string value);
		partial void OnTENDVChanged();
		partial void OnGIADVChanging(System.Nullable<decimal> value);
		partial void OnGIADVChanged();
		#endregion

		public DICHVU()
		{
			this._CT_DICHVUs = new EntitySet<CT_DICHVU>(new Action<CT_DICHVU>(this.attach_CT_DICHVUs), new Action<CT_DICHVU>(this.detach_CT_DICHVUs));
			this._CT_DICHVUs1 = new EntitySet<CT_DICHVU>(new Action<CT_DICHVU>(this.attach_CT_DICHVUs1), new Action<CT_DICHVU>(this.detach_CT_DICHVUs1));
			this._CT_DICHVUs2 = new EntitySet<CT_DICHVU>(new Action<CT_DICHVU>(this.attach_CT_DICHVUs2), new Action<CT_DICHVU>(this.detach_CT_DICHVUs2));
			OnCreated();
		}

		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_MADV", AutoSync = AutoSync.OnInsert, DbType = "BigInt NOT NULL IDENTITY", IsPrimaryKey = true, IsDbGenerated = true)]
		public long MADV
		{
			get
			{
				return this._MADV;
			}
			set
			{
				if ((this._MADV != value))
				{
					this.OnMADVChanging(value);
					this.SendPropertyChanging();
					this._MADV = value;
					this.SendPropertyChanged("MADV");
					this.OnMADVChanged();
				}
			}
		}

		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_TENDV", DbType = "NVarChar(100)")]
		public string TENDV
		{
			get
			{
				return this._TENDV;
			}
			set
			{
				if ((this._TENDV != value))
				{
					this.OnTENDVChanging(value);
					this.SendPropertyChanging();
					this._TENDV = value;
					this.SendPropertyChanged("TENDV");
					this.OnTENDVChanged();
				}
			}
		}

		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_GIADV", DbType = "Decimal(18,0)")]
		public System.Nullable<decimal> GIADV
		{
			get
			{
				return this._GIADV;
			}
			set
			{
				if ((this._GIADV != value))
				{
					this.OnGIADVChanging(value);
					this.SendPropertyChanging();
					this._GIADV = value;
					this.SendPropertyChanged("GIADV");
					this.OnGIADVChanged();
				}
			}
		}

		[global::System.Data.Linq.Mapping.AssociationAttribute(Name = "DICHVU_CT_DICHVU", Storage = "_CT_DICHVUs", ThisKey = "MADV", OtherKey = "MADV")]
		public EntitySet<CT_DICHVU> CT_DICHVUs
		{
			get
			{
				return this._CT_DICHVUs;
			}
			set
			{
				this._CT_DICHVUs.Assign(value);
			}
		}

		[global::System.Data.Linq.Mapping.AssociationAttribute(Name = "DICHVU_CT_DICHVU1", Storage = "_CT_DICHVUs1", ThisKey = "MADV", OtherKey = "MADV")]
		public EntitySet<CT_DICHVU> CT_DICHVUs1
		{
			get
			{
				return this._CT_DICHVUs1;
			}
			set
			{
				this._CT_DICHVUs1.Assign(value);
			}
		}

		[global::System.Data.Linq.Mapping.AssociationAttribute(Name = "DICHVU_CT_DICHVU2", Storage = "_CT_DICHVUs2", ThisKey = "MADV", OtherKey = "MADV")]
		public EntitySet<CT_DICHVU> CT_DICHVUs2
		{
			get
			{
				return this._CT_DICHVUs2;
			}
			set
			{
				this._CT_DICHVUs2.Assign(value);
			}
		}

		public event PropertyChangingEventHandler PropertyChanging;

		public event PropertyChangedEventHandler PropertyChanged;

		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}

		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}

		private void attach_CT_DICHVUs(CT_DICHVU entity)
		{
			this.SendPropertyChanging();
			entity.DICHVU = this;
		}

		private void detach_CT_DICHVUs(CT_DICHVU entity)
		{
			this.SendPropertyChanging();
			entity.DICHVU = null;
		}

		private void attach_CT_DICHVUs1(CT_DICHVU entity)
		{
			this.SendPropertyChanging();
			entity.DICHVU1 = this;
		}

		private void detach_CT_DICHVUs1(CT_DICHVU entity)
		{
			this.SendPropertyChanging();
			entity.DICHVU1 = null;
		}

		private void attach_CT_DICHVUs2(CT_DICHVU entity)
		{
			this.SendPropertyChanging();
			entity.DICHVU2 = this;
		}

		private void detach_CT_DICHVUs2(CT_DICHVU entity)
		{
			this.SendPropertyChanging();
			entity.DICHVU2 = null;
		}
	}

	[global::System.Data.Linq.Mapping.TableAttribute(Name = "dbo.KHACHHANG")]
	public partial class KHACHHANG : INotifyPropertyChanging, INotifyPropertyChanged
	{

		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);

		private long _MAKH;

		private string _TENKH;

		private string _TAIKHOAN_KH;

		private string _MATKHAU_KH;

		private string _EMAIL;

		private string _GIOITINH;

		private System.Nullable<System.DateTime> _NGAYSINH;

		private string _CMND_CCCD_KH;

		private EntitySet<PHIEUDATTOUR> _PHIEUDATTOURs;

		#region Extensibility Method Definitions
		partial void OnLoaded();
		partial void OnValidate(System.Data.Linq.ChangeAction action);
		partial void OnCreated();
		partial void OnMAKHChanging(long value);
		partial void OnMAKHChanged();
		partial void OnTENKHChanging(string value);
		partial void OnTENKHChanged();
		partial void OnTAIKHOAN_KHChanging(string value);
		partial void OnTAIKHOAN_KHChanged();
		partial void OnMATKHAU_KHChanging(string value);
		partial void OnMATKHAU_KHChanged();
		partial void OnEMAILChanging(string value);
		partial void OnEMAILChanged();
		partial void OnGIOITINHChanging(string value);
		partial void OnGIOITINHChanged();
		partial void OnNGAYSINHChanging(System.Nullable<System.DateTime> value);
		partial void OnNGAYSINHChanged();
		partial void OnCMND_CCCD_KHChanging(string value);
		partial void OnCMND_CCCD_KHChanged();
		#endregion

		public KHACHHANG()
		{
			this._PHIEUDATTOURs = new EntitySet<PHIEUDATTOUR>(new Action<PHIEUDATTOUR>(this.attach_PHIEUDATTOURs), new Action<PHIEUDATTOUR>(this.detach_PHIEUDATTOURs));
			OnCreated();
		}

		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_MAKH", AutoSync = AutoSync.OnInsert, DbType = "BigInt NOT NULL IDENTITY", IsPrimaryKey = true, IsDbGenerated = true)]
		public long MAKH
		{
			get
			{
				return this._MAKH;
			}
			set
			{
				if ((this._MAKH != value))
				{
					this.OnMAKHChanging(value);
					this.SendPropertyChanging();
					this._MAKH = value;
					this.SendPropertyChanged("MAKH");
					this.OnMAKHChanged();
				}
			}
		}

		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_TENKH", DbType = "NVarChar(100)")]
		public string TENKH
		{
			get
			{
				return this._TENKH;
			}
			set
			{
				if ((this._TENKH != value))
				{
					this.OnTENKHChanging(value);
					this.SendPropertyChanging();
					this._TENKH = value;
					this.SendPropertyChanged("TENKH");
					this.OnTENKHChanged();
				}
			}
		}

		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_TAIKHOAN_KH", DbType = "VarChar(100)")]
		public string TAIKHOAN_KH
		{
			get
			{
				return this._TAIKHOAN_KH;
			}
			set
			{
				if ((this._TAIKHOAN_KH != value))
				{
					this.OnTAIKHOAN_KHChanging(value);
					this.SendPropertyChanging();
					this._TAIKHOAN_KH = value;
					this.SendPropertyChanged("TAIKHOAN_KH");
					this.OnTAIKHOAN_KHChanged();
				}
			}
		}

		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_MATKHAU_KH", DbType = "VarChar(100)")]
		public string MATKHAU_KH
		{
			get
			{
				return this._MATKHAU_KH;
			}
			set
			{
				if ((this._MATKHAU_KH != value))
				{
					this.OnMATKHAU_KHChanging(value);
					this.SendPropertyChanging();
					this._MATKHAU_KH = value;
					this.SendPropertyChanged("MATKHAU_KH");
					this.OnMATKHAU_KHChanged();
				}
			}
		}

		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_EMAIL", DbType = "VarChar(200)")]
		public string EMAIL
		{
			get
			{
				return this._EMAIL;
			}
			set
			{
				if ((this._EMAIL != value))
				{
					this.OnEMAILChanging(value);
					this.SendPropertyChanging();
					this._EMAIL = value;
					this.SendPropertyChanged("EMAIL");
					this.OnEMAILChanged();
				}
			}
		}

		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_GIOITINH", DbType = "NVarChar(5)")]
		public string GIOITINH
		{
			get
			{
				return this._GIOITINH;
			}
			set
			{
				if ((this._GIOITINH != value))
				{
					this.OnGIOITINHChanging(value);
					this.SendPropertyChanging();
					this._GIOITINH = value;
					this.SendPropertyChanged("GIOITINH");
					this.OnGIOITINHChanged();
				}
			}
		}

		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_NGAYSINH", DbType = "DateTime")]
		public System.Nullable<System.DateTime> NGAYSINH
		{
			get
			{
				return this._NGAYSINH;
			}
			set
			{
				if ((this._NGAYSINH != value))
				{
					this.OnNGAYSINHChanging(value);
					this.SendPropertyChanging();
					this._NGAYSINH = value;
					this.SendPropertyChanged("NGAYSINH");
					this.OnNGAYSINHChanged();
				}
			}
		}

		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_CMND_CCCD_KH", DbType = "VarChar(100)")]
		public string CMND_CCCD_KH
		{
			get
			{
				return this._CMND_CCCD_KH;
			}
			set
			{
				if ((this._CMND_CCCD_KH != value))
				{
					this.OnCMND_CCCD_KHChanging(value);
					this.SendPropertyChanging();
					this._CMND_CCCD_KH = value;
					this.SendPropertyChanged("CMND_CCCD_KH");
					this.OnCMND_CCCD_KHChanged();
				}
			}
		}

		[global::System.Data.Linq.Mapping.AssociationAttribute(Name = "KHACHHANG_PHIEUDATTOUR", Storage = "_PHIEUDATTOURs", ThisKey = "MAKH", OtherKey = "MAKH")]
		public EntitySet<PHIEUDATTOUR> PHIEUDATTOURs
		{
			get
			{
				return this._PHIEUDATTOURs;
			}
			set
			{
				this._PHIEUDATTOURs.Assign(value);
			}
		}

		public event PropertyChangingEventHandler PropertyChanging;

		public event PropertyChangedEventHandler PropertyChanged;

		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}

		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}

		private void attach_PHIEUDATTOURs(PHIEUDATTOUR entity)
		{
			this.SendPropertyChanging();
			entity.KHACHHANG = this;
		}

		private void detach_PHIEUDATTOURs(PHIEUDATTOUR entity)
		{
			this.SendPropertyChanging();
			entity.KHACHHANG = null;
		}
	}

	[global::System.Data.Linq.Mapping.TableAttribute(Name = "dbo.LOAITOUR")]
	public partial class LOAITOUR : INotifyPropertyChanging, INotifyPropertyChanged
	{

		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);

		private long _MALOAITOUR;

		private string _TENLOAITOUR;

		private System.Nullable<int> _SOLUONG;

		private EntitySet<TOURDL> _TOURDLs;

		private EntitySet<TOURDL> _TOURDLs1;

		private EntitySet<TOURDL> _TOURDLs2;

		#region Extensibility Method Definitions
		partial void OnLoaded();
		partial void OnValidate(System.Data.Linq.ChangeAction action);
		partial void OnCreated();
		partial void OnMALOAITOURChanging(long value);
		partial void OnMALOAITOURChanged();
		partial void OnTENLOAITOURChanging(string value);
		partial void OnTENLOAITOURChanged();
		partial void OnSOLUONGChanging(System.Nullable<int> value);
		partial void OnSOLUONGChanged();
		#endregion

		public LOAITOUR()
		{
			this._TOURDLs = new EntitySet<TOURDL>(new Action<TOURDL>(this.attach_TOURDLs), new Action<TOURDL>(this.detach_TOURDLs));
			this._TOURDLs1 = new EntitySet<TOURDL>(new Action<TOURDL>(this.attach_TOURDLs1), new Action<TOURDL>(this.detach_TOURDLs1));
			this._TOURDLs2 = new EntitySet<TOURDL>(new Action<TOURDL>(this.attach_TOURDLs2), new Action<TOURDL>(this.detach_TOURDLs2));
			OnCreated();
		}

		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_MALOAITOUR", AutoSync = AutoSync.OnInsert, DbType = "BigInt NOT NULL IDENTITY", IsPrimaryKey = true, IsDbGenerated = true)]
		public long MALOAITOUR
		{
			get
			{
				return this._MALOAITOUR;
			}
			set
			{
				if ((this._MALOAITOUR != value))
				{
					this.OnMALOAITOURChanging(value);
					this.SendPropertyChanging();
					this._MALOAITOUR = value;
					this.SendPropertyChanged("MALOAITOUR");
					this.OnMALOAITOURChanged();
				}
			}
		}

		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_TENLOAITOUR", DbType = "NVarChar(100)")]
		public string TENLOAITOUR
		{
			get
			{
				return this._TENLOAITOUR;
			}
			set
			{
				if ((this._TENLOAITOUR != value))
				{
					this.OnTENLOAITOURChanging(value);
					this.SendPropertyChanging();
					this._TENLOAITOUR = value;
					this.SendPropertyChanged("TENLOAITOUR");
					this.OnTENLOAITOURChanged();
				}
			}
		}

		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_SOLUONG", DbType = "Int")]
		public System.Nullable<int> SOLUONG
		{
			get
			{
				return this._SOLUONG;
			}
			set
			{
				if ((this._SOLUONG != value))
				{
					this.OnSOLUONGChanging(value);
					this.SendPropertyChanging();
					this._SOLUONG = value;
					this.SendPropertyChanged("SOLUONG");
					this.OnSOLUONGChanged();
				}
			}
		}

		[global::System.Data.Linq.Mapping.AssociationAttribute(Name = "LOAITOUR_TOURDL", Storage = "_TOURDLs", ThisKey = "MALOAITOUR", OtherKey = "MALOAITOUR")]
		public EntitySet<TOURDL> TOURDLs
		{
			get
			{
				return this._TOURDLs;
			}
			set
			{
				this._TOURDLs.Assign(value);
			}
		}

		[global::System.Data.Linq.Mapping.AssociationAttribute(Name = "LOAITOUR_TOURDL1", Storage = "_TOURDLs1", ThisKey = "MALOAITOUR", OtherKey = "MALOAITOUR")]
		public EntitySet<TOURDL> TOURDLs1
		{
			get
			{
				return this._TOURDLs1;
			}
			set
			{
				this._TOURDLs1.Assign(value);
			}
		}

		[global::System.Data.Linq.Mapping.AssociationAttribute(Name = "LOAITOUR_TOURDL2", Storage = "_TOURDLs2", ThisKey = "MALOAITOUR", OtherKey = "MALOAITOUR")]
		public EntitySet<TOURDL> TOURDLs2
		{
			get
			{
				return this._TOURDLs2;
			}
			set
			{
				this._TOURDLs2.Assign(value);
			}
		}

		public event PropertyChangingEventHandler PropertyChanging;

		public event PropertyChangedEventHandler PropertyChanged;

		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}

		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}

		private void attach_TOURDLs(TOURDL entity)
		{
			this.SendPropertyChanging();
			entity.LOAITOUR = this;
		}

		private void detach_TOURDLs(TOURDL entity)
		{
			this.SendPropertyChanging();
			entity.LOAITOUR = null;
		}

		private void attach_TOURDLs1(TOURDL entity)
		{
			this.SendPropertyChanging();
			entity.LOAITOUR1 = this;
		}

		private void detach_TOURDLs1(TOURDL entity)
		{
			this.SendPropertyChanging();
			entity.LOAITOUR1 = null;
		}

		private void attach_TOURDLs2(TOURDL entity)
		{
			this.SendPropertyChanging();
			entity.LOAITOUR2 = this;
		}

		private void detach_TOURDLs2(TOURDL entity)
		{
			this.SendPropertyChanging();
			entity.LOAITOUR2 = null;
		}
	}

	[global::System.Data.Linq.Mapping.TableAttribute(Name = "dbo.NHANVIEN")]
	public partial class NHANVIEN : INotifyPropertyChanging, INotifyPropertyChanged
	{

		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);

		private long _MANV;

		private string _TAIKHOAN_NV;

		private string _MATKHAU_NV;

		private string _TENNV;

		private string _GIOITINH;

		private System.Nullable<System.DateTime> _NGAYSINH;

		private string _CMND_CCCD_NV;

		private EntitySet<PHIEUDATTOUR> _PHIEUDATTOURs;

		private EntitySet<PHIEUDATTOUR> _PHIEUDATTOURs1;

		#region Extensibility Method Definitions
		partial void OnLoaded();
		partial void OnValidate(System.Data.Linq.ChangeAction action);
		partial void OnCreated();
		partial void OnMANVChanging(long value);
		partial void OnMANVChanged();
		partial void OnTAIKHOAN_NVChanging(string value);
		partial void OnTAIKHOAN_NVChanged();
		partial void OnMATKHAU_NVChanging(string value);
		partial void OnMATKHAU_NVChanged();
		partial void OnTENNVChanging(string value);
		partial void OnTENNVChanged();
		partial void OnGIOITINHChanging(string value);
		partial void OnGIOITINHChanged();
		partial void OnNGAYSINHChanging(System.Nullable<System.DateTime> value);
		partial void OnNGAYSINHChanged();
		partial void OnCMND_CCCD_NVChanging(string value);
		partial void OnCMND_CCCD_NVChanged();
		#endregion

		public NHANVIEN()
		{
			this._PHIEUDATTOURs = new EntitySet<PHIEUDATTOUR>(new Action<PHIEUDATTOUR>(this.attach_PHIEUDATTOURs), new Action<PHIEUDATTOUR>(this.detach_PHIEUDATTOURs));
			this._PHIEUDATTOURs1 = new EntitySet<PHIEUDATTOUR>(new Action<PHIEUDATTOUR>(this.attach_PHIEUDATTOURs1), new Action<PHIEUDATTOUR>(this.detach_PHIEUDATTOURs1));
			OnCreated();
		}

		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_MANV", AutoSync = AutoSync.OnInsert, DbType = "BigInt NOT NULL IDENTITY", IsPrimaryKey = true, IsDbGenerated = true)]
		public long MANV
		{
			get
			{
				return this._MANV;
			}
			set
			{
				if ((this._MANV != value))
				{
					this.OnMANVChanging(value);
					this.SendPropertyChanging();
					this._MANV = value;
					this.SendPropertyChanged("MANV");
					this.OnMANVChanged();
				}
			}
		}

		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_TAIKHOAN_NV", DbType = "VarChar(100)")]
		public string TAIKHOAN_NV
		{
			get
			{
				return this._TAIKHOAN_NV;
			}
			set
			{
				if ((this._TAIKHOAN_NV != value))
				{
					this.OnTAIKHOAN_NVChanging(value);
					this.SendPropertyChanging();
					this._TAIKHOAN_NV = value;
					this.SendPropertyChanged("TAIKHOAN_NV");
					this.OnTAIKHOAN_NVChanged();
				}
			}
		}

		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_MATKHAU_NV", DbType = "VarChar(100)")]
		public string MATKHAU_NV
		{
			get
			{
				return this._MATKHAU_NV;
			}
			set
			{
				if ((this._MATKHAU_NV != value))
				{
					this.OnMATKHAU_NVChanging(value);
					this.SendPropertyChanging();
					this._MATKHAU_NV = value;
					this.SendPropertyChanged("MATKHAU_NV");
					this.OnMATKHAU_NVChanged();
				}
			}
		}

		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_TENNV", DbType = "NVarChar(100)")]
		public string TENNV
		{
			get
			{
				return this._TENNV;
			}
			set
			{
				if ((this._TENNV != value))
				{
					this.OnTENNVChanging(value);
					this.SendPropertyChanging();
					this._TENNV = value;
					this.SendPropertyChanged("TENNV");
					this.OnTENNVChanged();
				}
			}
		}

		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_GIOITINH", DbType = "NVarChar(5)")]
		public string GIOITINH
		{
			get
			{
				return this._GIOITINH;
			}
			set
			{
				if ((this._GIOITINH != value))
				{
					this.OnGIOITINHChanging(value);
					this.SendPropertyChanging();
					this._GIOITINH = value;
					this.SendPropertyChanged("GIOITINH");
					this.OnGIOITINHChanged();
				}
			}
		}

		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_NGAYSINH", DbType = "DateTime")]
		public System.Nullable<System.DateTime> NGAYSINH
		{
			get
			{
				return this._NGAYSINH;
			}
			set
			{
				if ((this._NGAYSINH != value))
				{
					this.OnNGAYSINHChanging(value);
					this.SendPropertyChanging();
					this._NGAYSINH = value;
					this.SendPropertyChanged("NGAYSINH");
					this.OnNGAYSINHChanged();
				}
			}
		}

		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_CMND_CCCD_NV", DbType = "VarChar(100)")]
		public string CMND_CCCD_NV
		{
			get
			{
				return this._CMND_CCCD_NV;
			}
			set
			{
				if ((this._CMND_CCCD_NV != value))
				{
					this.OnCMND_CCCD_NVChanging(value);
					this.SendPropertyChanging();
					this._CMND_CCCD_NV = value;
					this.SendPropertyChanged("CMND_CCCD_NV");
					this.OnCMND_CCCD_NVChanged();
				}
			}
		}

		[global::System.Data.Linq.Mapping.AssociationAttribute(Name = "NHANVIEN_PHIEUDATTOUR", Storage = "_PHIEUDATTOURs", ThisKey = "MANV", OtherKey = "MANV")]
		public EntitySet<PHIEUDATTOUR> PHIEUDATTOURs
		{
			get
			{
				return this._PHIEUDATTOURs;
			}
			set
			{
				this._PHIEUDATTOURs.Assign(value);
			}
		}

		[global::System.Data.Linq.Mapping.AssociationAttribute(Name = "NHANVIEN_PHIEUDATTOUR1", Storage = "_PHIEUDATTOURs1", ThisKey = "MANV", OtherKey = "MANV")]
		public EntitySet<PHIEUDATTOUR> PHIEUDATTOURs1
		{
			get
			{
				return this._PHIEUDATTOURs1;
			}
			set
			{
				this._PHIEUDATTOURs1.Assign(value);
			}
		}

		public event PropertyChangingEventHandler PropertyChanging;

		public event PropertyChangedEventHandler PropertyChanged;

		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}

		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}

		private void attach_PHIEUDATTOURs(PHIEUDATTOUR entity)
		{
			this.SendPropertyChanging();
			entity.NHANVIEN = this;
		}

		private void detach_PHIEUDATTOURs(PHIEUDATTOUR entity)
		{
			this.SendPropertyChanging();
			entity.NHANVIEN = null;
		}

		private void attach_PHIEUDATTOURs1(PHIEUDATTOUR entity)
		{
			this.SendPropertyChanging();
			entity.NHANVIEN1 = this;
		}

		private void detach_PHIEUDATTOURs1(PHIEUDATTOUR entity)
		{
			this.SendPropertyChanging();
			entity.NHANVIEN1 = null;
		}
	}

	[global::System.Data.Linq.Mapping.TableAttribute(Name = "dbo.PHIEUDATTOUR")]
	public partial class PHIEUDATTOUR : INotifyPropertyChanging, INotifyPropertyChanged
	{

		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);

		private long _MAPDT;

		private long _MANV;

		private long _MAKH;

		private System.Nullable<System.DateTime> _NGAYDAT;

		private System.Nullable<decimal> _TONGTIEN;

		private EntitySet<CT_DICHVU> _CT_DICHVUs;

		private EntitySet<CT_DICHVU> _CT_DICHVUs1;

		private EntitySet<CT_TOUR> _CT_TOURs;

		private EntitySet<CT_TOUR> _CT_TOURs1;

		private EntitySet<CT_TOUR> _CT_TOURs2;

		private EntityRef<KHACHHANG> _KHACHHANG;

		private EntityRef<NHANVIEN> _NHANVIEN;

		private EntityRef<NHANVIEN> _NHANVIEN1;

		#region Extensibility Method Definitions
		partial void OnLoaded();
		partial void OnValidate(System.Data.Linq.ChangeAction action);
		partial void OnCreated();
		partial void OnMAPDTChanging(long value);
		partial void OnMAPDTChanged();
		partial void OnMANVChanging(long value);
		partial void OnMANVChanged();
		partial void OnMAKHChanging(long value);
		partial void OnMAKHChanged();
		partial void OnNGAYDATChanging(System.Nullable<System.DateTime> value);
		partial void OnNGAYDATChanged();
		partial void OnTONGTIENChanging(System.Nullable<decimal> value);
		partial void OnTONGTIENChanged();
		#endregion

		public PHIEUDATTOUR()
		{
			this._CT_DICHVUs = new EntitySet<CT_DICHVU>(new Action<CT_DICHVU>(this.attach_CT_DICHVUs), new Action<CT_DICHVU>(this.detach_CT_DICHVUs));
			this._CT_DICHVUs1 = new EntitySet<CT_DICHVU>(new Action<CT_DICHVU>(this.attach_CT_DICHVUs1), new Action<CT_DICHVU>(this.detach_CT_DICHVUs1));
			this._CT_TOURs = new EntitySet<CT_TOUR>(new Action<CT_TOUR>(this.attach_CT_TOURs), new Action<CT_TOUR>(this.detach_CT_TOURs));
			this._CT_TOURs1 = new EntitySet<CT_TOUR>(new Action<CT_TOUR>(this.attach_CT_TOURs1), new Action<CT_TOUR>(this.detach_CT_TOURs1));
			this._CT_TOURs2 = new EntitySet<CT_TOUR>(new Action<CT_TOUR>(this.attach_CT_TOURs2), new Action<CT_TOUR>(this.detach_CT_TOURs2));
			this._KHACHHANG = default(EntityRef<KHACHHANG>);
			this._NHANVIEN = default(EntityRef<NHANVIEN>);
			this._NHANVIEN1 = default(EntityRef<NHANVIEN>);
			OnCreated();
		}

		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_MAPDT", AutoSync = AutoSync.OnInsert, DbType = "BigInt NOT NULL IDENTITY", IsPrimaryKey = true, IsDbGenerated = true)]
		public long MAPDT
		{
			get
			{
				return this._MAPDT;
			}
			set
			{
				if ((this._MAPDT != value))
				{
					this.OnMAPDTChanging(value);
					this.SendPropertyChanging();
					this._MAPDT = value;
					this.SendPropertyChanged("MAPDT");
					this.OnMAPDTChanged();
				}
			}
		}

		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_MANV", DbType = "BigInt NOT NULL")]
		public long MANV
		{
			get
			{
				return this._MANV;
			}
			set
			{
				if ((this._MANV != value))
				{
					if ((this._NHANVIEN.HasLoadedOrAssignedValue || this._NHANVIEN1.HasLoadedOrAssignedValue))
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMANVChanging(value);
					this.SendPropertyChanging();
					this._MANV = value;
					this.SendPropertyChanged("MANV");
					this.OnMANVChanged();
				}
			}
		}

		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_MAKH", DbType = "BigInt NOT NULL")]
		public long MAKH
		{
			get
			{
				return this._MAKH;
			}
			set
			{
				if ((this._MAKH != value))
				{
					if (this._KHACHHANG.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMAKHChanging(value);
					this.SendPropertyChanging();
					this._MAKH = value;
					this.SendPropertyChanged("MAKH");
					this.OnMAKHChanged();
				}
			}
		}

		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_NGAYDAT", DbType = "DateTime")]
		public System.Nullable<System.DateTime> NGAYDAT
		{
			get
			{
				return this._NGAYDAT;
			}
			set
			{
				if ((this._NGAYDAT != value))
				{
					this.OnNGAYDATChanging(value);
					this.SendPropertyChanging();
					this._NGAYDAT = value;
					this.SendPropertyChanged("NGAYDAT");
					this.OnNGAYDATChanged();
				}
			}
		}

		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_TONGTIEN", DbType = "Decimal(18,0)")]
		public System.Nullable<decimal> TONGTIEN
		{
			get
			{
				return this._TONGTIEN;
			}
			set
			{
				if ((this._TONGTIEN != value))
				{
					this.OnTONGTIENChanging(value);
					this.SendPropertyChanging();
					this._TONGTIEN = value;
					this.SendPropertyChanged("TONGTIEN");
					this.OnTONGTIENChanged();
				}
			}
		}

		[global::System.Data.Linq.Mapping.AssociationAttribute(Name = "PHIEUDATTOUR_CT_DICHVU", Storage = "_CT_DICHVUs", ThisKey = "MAPDT", OtherKey = "MAPDT")]
		public EntitySet<CT_DICHVU> CT_DICHVUs
		{
			get
			{
				return this._CT_DICHVUs;
			}
			set
			{
				this._CT_DICHVUs.Assign(value);
			}
		}

		[global::System.Data.Linq.Mapping.AssociationAttribute(Name = "PHIEUDATTOUR_CT_DICHVU1", Storage = "_CT_DICHVUs1", ThisKey = "MAPDT", OtherKey = "MAPDT")]
		public EntitySet<CT_DICHVU> CT_DICHVUs1
		{
			get
			{
				return this._CT_DICHVUs1;
			}
			set
			{
				this._CT_DICHVUs1.Assign(value);
			}
		}

		[global::System.Data.Linq.Mapping.AssociationAttribute(Name = "PHIEUDATTOUR_CT_TOUR", Storage = "_CT_TOURs", ThisKey = "MAPDT", OtherKey = "MAPDT")]
		public EntitySet<CT_TOUR> CT_TOURs
		{
			get
			{
				return this._CT_TOURs;
			}
			set
			{
				this._CT_TOURs.Assign(value);
			}
		}

		[global::System.Data.Linq.Mapping.AssociationAttribute(Name = "PHIEUDATTOUR_CT_TOUR1", Storage = "_CT_TOURs1", ThisKey = "MAPDT", OtherKey = "MAPDT")]
		public EntitySet<CT_TOUR> CT_TOURs1
		{
			get
			{
				return this._CT_TOURs1;
			}
			set
			{
				this._CT_TOURs1.Assign(value);
			}
		}

		[global::System.Data.Linq.Mapping.AssociationAttribute(Name = "PHIEUDATTOUR_CT_TOUR2", Storage = "_CT_TOURs2", ThisKey = "MAPDT", OtherKey = "MAPDT")]
		public EntitySet<CT_TOUR> CT_TOURs2
		{
			get
			{
				return this._CT_TOURs2;
			}
			set
			{
				this._CT_TOURs2.Assign(value);
			}
		}

		[global::System.Data.Linq.Mapping.AssociationAttribute(Name = "KHACHHANG_PHIEUDATTOUR", Storage = "_KHACHHANG", ThisKey = "MAKH", OtherKey = "MAKH", IsForeignKey = true)]
		public KHACHHANG KHACHHANG
		{
			get
			{
				return this._KHACHHANG.Entity;
			}
			set
			{
				KHACHHANG previousValue = this._KHACHHANG.Entity;
				if (((previousValue != value)
							|| (this._KHACHHANG.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._KHACHHANG.Entity = null;
						previousValue.PHIEUDATTOURs.Remove(this);
					}
					this._KHACHHANG.Entity = value;
					if ((value != null))
					{
						value.PHIEUDATTOURs.Add(this);
						this._MAKH = value.MAKH;
					}
					else
					{
						this._MAKH = default(long);
					}
					this.SendPropertyChanged("KHACHHANG");
				}
			}
		}

		[global::System.Data.Linq.Mapping.AssociationAttribute(Name = "NHANVIEN_PHIEUDATTOUR", Storage = "_NHANVIEN", ThisKey = "MANV", OtherKey = "MANV", IsForeignKey = true)]
		public NHANVIEN NHANVIEN
		{
			get
			{
				return this._NHANVIEN.Entity;
			}
			set
			{
				NHANVIEN previousValue = this._NHANVIEN.Entity;
				if (((previousValue != value)
							|| (this._NHANVIEN.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NHANVIEN.Entity = null;
						previousValue.PHIEUDATTOURs.Remove(this);
					}
					this._NHANVIEN.Entity = value;
					if ((value != null))
					{
						value.PHIEUDATTOURs.Add(this);
						this._MANV = value.MANV;
					}
					else
					{
						this._MANV = default(long);
					}
					this.SendPropertyChanged("NHANVIEN");
				}
			}
		}

		[global::System.Data.Linq.Mapping.AssociationAttribute(Name = "NHANVIEN_PHIEUDATTOUR1", Storage = "_NHANVIEN1", ThisKey = "MANV", OtherKey = "MANV", IsForeignKey = true)]
		public NHANVIEN NHANVIEN1
		{
			get
			{
				return this._NHANVIEN1.Entity;
			}
			set
			{
				NHANVIEN previousValue = this._NHANVIEN1.Entity;
				if (((previousValue != value)
							|| (this._NHANVIEN1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NHANVIEN1.Entity = null;
						previousValue.PHIEUDATTOURs1.Remove(this);
					}
					this._NHANVIEN1.Entity = value;
					if ((value != null))
					{
						value.PHIEUDATTOURs1.Add(this);
						this._MANV = value.MANV;
					}
					else
					{
						this._MANV = default(long);
					}
					this.SendPropertyChanged("NHANVIEN1");
				}
			}
		}

		public event PropertyChangingEventHandler PropertyChanging;

		public event PropertyChangedEventHandler PropertyChanged;

		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}

		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}

		private void attach_CT_DICHVUs(CT_DICHVU entity)
		{
			this.SendPropertyChanging();
			entity.PHIEUDATTOUR = this;
		}

		private void detach_CT_DICHVUs(CT_DICHVU entity)
		{
			this.SendPropertyChanging();
			entity.PHIEUDATTOUR = null;
		}

		private void attach_CT_DICHVUs1(CT_DICHVU entity)
		{
			this.SendPropertyChanging();
			entity.PHIEUDATTOUR1 = this;
		}

		private void detach_CT_DICHVUs1(CT_DICHVU entity)
		{
			this.SendPropertyChanging();
			entity.PHIEUDATTOUR1 = null;
		}

		private void attach_CT_TOURs(CT_TOUR entity)
		{
			this.SendPropertyChanging();
			entity.PHIEUDATTOUR = this;
		}

		private void detach_CT_TOURs(CT_TOUR entity)
		{
			this.SendPropertyChanging();
			entity.PHIEUDATTOUR = null;
		}

		private void attach_CT_TOURs1(CT_TOUR entity)
		{
			this.SendPropertyChanging();
			entity.PHIEUDATTOUR1 = this;
		}

		private void detach_CT_TOURs1(CT_TOUR entity)
		{
			this.SendPropertyChanging();
			entity.PHIEUDATTOUR1 = null;
		}

		private void attach_CT_TOURs2(CT_TOUR entity)
		{
			this.SendPropertyChanging();
			entity.PHIEUDATTOUR2 = this;
		}

		private void detach_CT_TOURs2(CT_TOUR entity)
		{
			this.SendPropertyChanging();
			entity.PHIEUDATTOUR2 = null;
		}
	}

	[global::System.Data.Linq.Mapping.TableAttribute(Name = "dbo.TOURDL")]
	public partial class TOURDL : INotifyPropertyChanging, INotifyPropertyChanged
	{

		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);

		private long _MATOUR;

		private long _MADIADIEM;

		private long _MALOAITOUR;

		private string _TENTOUR;

		private string _HINHTOUR;

		private System.Nullable<decimal> _GIATOUR;

		private EntitySet<CT_TOUR> _CT_TOURs;

		private EntitySet<CT_TOUR> _CT_TOURs1;

		private EntitySet<CT_TOUR> _CT_TOURs2;

		private EntityRef<DIADIEM> _DIADIEM;

		private EntityRef<DIADIEM> _DIADIEM1;

		private EntityRef<DIADIEM> _DIADIEM2;

		private EntityRef<LOAITOUR> _LOAITOUR;

		private EntityRef<LOAITOUR> _LOAITOUR1;

		private EntityRef<LOAITOUR> _LOAITOUR2;

		#region Extensibility Method Definitions
		partial void OnLoaded();
		partial void OnValidate(System.Data.Linq.ChangeAction action);
		partial void OnCreated();
		partial void OnMATOURChanging(long value);
		partial void OnMATOURChanged();
		partial void OnMADIADIEMChanging(long value);
		partial void OnMADIADIEMChanged();
		partial void OnMALOAITOURChanging(long value);
		partial void OnMALOAITOURChanged();
		partial void OnTENTOURChanging(string value);
		partial void OnTENTOURChanged();
		partial void OnHINHTOURChanging(string value);
		partial void OnHINHTOURChanged();
		partial void OnGIATOURChanging(System.Nullable<decimal> value);
		partial void OnGIATOURChanged();
		#endregion

		public TOURDL()
		{
			this._CT_TOURs = new EntitySet<CT_TOUR>(new Action<CT_TOUR>(this.attach_CT_TOURs), new Action<CT_TOUR>(this.detach_CT_TOURs));
			this._CT_TOURs1 = new EntitySet<CT_TOUR>(new Action<CT_TOUR>(this.attach_CT_TOURs1), new Action<CT_TOUR>(this.detach_CT_TOURs1));
			this._CT_TOURs2 = new EntitySet<CT_TOUR>(new Action<CT_TOUR>(this.attach_CT_TOURs2), new Action<CT_TOUR>(this.detach_CT_TOURs2));
			this._DIADIEM = default(EntityRef<DIADIEM>);
			this._DIADIEM1 = default(EntityRef<DIADIEM>);
			this._DIADIEM2 = default(EntityRef<DIADIEM>);
			this._LOAITOUR = default(EntityRef<LOAITOUR>);
			this._LOAITOUR1 = default(EntityRef<LOAITOUR>);
			this._LOAITOUR2 = default(EntityRef<LOAITOUR>);
			OnCreated();
		}

		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_MATOUR", AutoSync = AutoSync.OnInsert, DbType = "BigInt NOT NULL IDENTITY", IsPrimaryKey = true, IsDbGenerated = true)]
		public long MATOUR
		{
			get
			{
				return this._MATOUR;
			}
			set
			{
				if ((this._MATOUR != value))
				{
					this.OnMATOURChanging(value);
					this.SendPropertyChanging();
					this._MATOUR = value;
					this.SendPropertyChanged("MATOUR");
					this.OnMATOURChanged();
				}
			}
		}

		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_MADIADIEM", DbType = "BigInt NOT NULL")]
		public long MADIADIEM
		{
			get
			{
				return this._MADIADIEM;
			}
			set
			{
				if ((this._MADIADIEM != value))
				{
					if (((this._DIADIEM.HasLoadedOrAssignedValue || this._DIADIEM1.HasLoadedOrAssignedValue)
								|| this._DIADIEM2.HasLoadedOrAssignedValue))
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMADIADIEMChanging(value);
					this.SendPropertyChanging();
					this._MADIADIEM = value;
					this.SendPropertyChanged("MADIADIEM");
					this.OnMADIADIEMChanged();
				}
			}
		}

		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_MALOAITOUR", DbType = "BigInt NOT NULL")]
		public long MALOAITOUR
		{
			get
			{
				return this._MALOAITOUR;
			}
			set
			{
				if ((this._MALOAITOUR != value))
				{
					if (((this._LOAITOUR.HasLoadedOrAssignedValue || this._LOAITOUR1.HasLoadedOrAssignedValue)
								|| this._LOAITOUR2.HasLoadedOrAssignedValue))
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMALOAITOURChanging(value);
					this.SendPropertyChanging();
					this._MALOAITOUR = value;
					this.SendPropertyChanged("MALOAITOUR");
					this.OnMALOAITOURChanged();
				}
			}
		}

		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_TENTOUR", DbType = "NVarChar(100)")]
		public string TENTOUR
		{
			get
			{
				return this._TENTOUR;
			}
			set
			{
				if ((this._TENTOUR != value))
				{
					this.OnTENTOURChanging(value);
					this.SendPropertyChanging();
					this._TENTOUR = value;
					this.SendPropertyChanged("TENTOUR");
					this.OnTENTOURChanged();
				}
			}
		}

		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_HINHTOUR", DbType = "VarChar(100)")]
		public string HINHTOUR
		{
			get
			{
				return this._HINHTOUR;
			}
			set
			{
				if ((this._HINHTOUR != value))
				{
					this.OnHINHTOURChanging(value);
					this.SendPropertyChanging();
					this._HINHTOUR = value;
					this.SendPropertyChanged("HINHTOUR");
					this.OnHINHTOURChanged();
				}
			}
		}

		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_GIATOUR", DbType = "Decimal(18,0)")]
		public System.Nullable<decimal> GIATOUR
		{
			get
			{
				return this._GIATOUR;
			}
			set
			{
				if ((this._GIATOUR != value))
				{
					this.OnGIATOURChanging(value);
					this.SendPropertyChanging();
					this._GIATOUR = value;
					this.SendPropertyChanged("GIATOUR");
					this.OnGIATOURChanged();
				}
			}
		}

		[global::System.Data.Linq.Mapping.AssociationAttribute(Name = "TOURDL_CT_TOUR", Storage = "_CT_TOURs", ThisKey = "MATOUR", OtherKey = "MATOUR")]
		public EntitySet<CT_TOUR> CT_TOURs
		{
			get
			{
				return this._CT_TOURs;
			}
			set
			{
				this._CT_TOURs.Assign(value);
			}
		}

		[global::System.Data.Linq.Mapping.AssociationAttribute(Name = "TOURDL_CT_TOUR1", Storage = "_CT_TOURs1", ThisKey = "MATOUR", OtherKey = "MATOUR")]
		public EntitySet<CT_TOUR> CT_TOURs1
		{
			get
			{
				return this._CT_TOURs1;
			}
			set
			{
				this._CT_TOURs1.Assign(value);
			}
		}

		[global::System.Data.Linq.Mapping.AssociationAttribute(Name = "TOURDL_CT_TOUR2", Storage = "_CT_TOURs2", ThisKey = "MATOUR", OtherKey = "MATOUR")]
		public EntitySet<CT_TOUR> CT_TOURs2
		{
			get
			{
				return this._CT_TOURs2;
			}
			set
			{
				this._CT_TOURs2.Assign(value);
			}
		}

		[global::System.Data.Linq.Mapping.AssociationAttribute(Name = "DIADIEM_TOURDL", Storage = "_DIADIEM", ThisKey = "MADIADIEM", OtherKey = "MADIADIEM", IsForeignKey = true)]
		public DIADIEM DIADIEM
		{
			get
			{
				return this._DIADIEM.Entity;
			}
			set
			{
				DIADIEM previousValue = this._DIADIEM.Entity;
				if (((previousValue != value)
							|| (this._DIADIEM.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._DIADIEM.Entity = null;
						previousValue.TOURDLs.Remove(this);
					}
					this._DIADIEM.Entity = value;
					if ((value != null))
					{
						value.TOURDLs.Add(this);
						this._MADIADIEM = value.MADIADIEM;
					}
					else
					{
						this._MADIADIEM = default(long);
					}
					this.SendPropertyChanged("DIADIEM");
				}
			}
		}

		[global::System.Data.Linq.Mapping.AssociationAttribute(Name = "DIADIEM_TOURDL1", Storage = "_DIADIEM1", ThisKey = "MADIADIEM", OtherKey = "MADIADIEM", IsForeignKey = true)]
		public DIADIEM DIADIEM1
		{
			get
			{
				return this._DIADIEM1.Entity;
			}
			set
			{
				DIADIEM previousValue = this._DIADIEM1.Entity;
				if (((previousValue != value)
							|| (this._DIADIEM1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._DIADIEM1.Entity = null;
						previousValue.TOURDLs1.Remove(this);
					}
					this._DIADIEM1.Entity = value;
					if ((value != null))
					{
						value.TOURDLs1.Add(this);
						this._MADIADIEM = value.MADIADIEM;
					}
					else
					{
						this._MADIADIEM = default(long);
					}
					this.SendPropertyChanged("DIADIEM1");
				}
			}
		}

		[global::System.Data.Linq.Mapping.AssociationAttribute(Name = "DIADIEM_TOURDL2", Storage = "_DIADIEM2", ThisKey = "MADIADIEM", OtherKey = "MADIADIEM", IsForeignKey = true)]
		public DIADIEM DIADIEM2
		{
			get
			{
				return this._DIADIEM2.Entity;
			}
			set
			{
				DIADIEM previousValue = this._DIADIEM2.Entity;
				if (((previousValue != value)
							|| (this._DIADIEM2.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._DIADIEM2.Entity = null;
						previousValue.TOURDLs2.Remove(this);
					}
					this._DIADIEM2.Entity = value;
					if ((value != null))
					{
						value.TOURDLs2.Add(this);
						this._MADIADIEM = value.MADIADIEM;
					}
					else
					{
						this._MADIADIEM = default(long);
					}
					this.SendPropertyChanged("DIADIEM2");
				}
			}
		}

		[global::System.Data.Linq.Mapping.AssociationAttribute(Name = "LOAITOUR_TOURDL", Storage = "_LOAITOUR", ThisKey = "MALOAITOUR", OtherKey = "MALOAITOUR", IsForeignKey = true)]
		public LOAITOUR LOAITOUR
		{
			get
			{
				return this._LOAITOUR.Entity;
			}
			set
			{
				LOAITOUR previousValue = this._LOAITOUR.Entity;
				if (((previousValue != value)
							|| (this._LOAITOUR.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._LOAITOUR.Entity = null;
						previousValue.TOURDLs.Remove(this);
					}
					this._LOAITOUR.Entity = value;
					if ((value != null))
					{
						value.TOURDLs.Add(this);
						this._MALOAITOUR = value.MALOAITOUR;
					}
					else
					{
						this._MALOAITOUR = default(long);
					}
					this.SendPropertyChanged("LOAITOUR");
				}
			}
		}

		[global::System.Data.Linq.Mapping.AssociationAttribute(Name = "LOAITOUR_TOURDL1", Storage = "_LOAITOUR1", ThisKey = "MALOAITOUR", OtherKey = "MALOAITOUR", IsForeignKey = true)]
		public LOAITOUR LOAITOUR1
		{
			get
			{
				return this._LOAITOUR1.Entity;
			}
			set
			{
				LOAITOUR previousValue = this._LOAITOUR1.Entity;
				if (((previousValue != value)
							|| (this._LOAITOUR1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._LOAITOUR1.Entity = null;
						previousValue.TOURDLs1.Remove(this);
					}
					this._LOAITOUR1.Entity = value;
					if ((value != null))
					{
						value.TOURDLs1.Add(this);
						this._MALOAITOUR = value.MALOAITOUR;
					}
					else
					{
						this._MALOAITOUR = default(long);
					}
					this.SendPropertyChanged("LOAITOUR1");
				}
			}
		}

		[global::System.Data.Linq.Mapping.AssociationAttribute(Name = "LOAITOUR_TOURDL2", Storage = "_LOAITOUR2", ThisKey = "MALOAITOUR", OtherKey = "MALOAITOUR", IsForeignKey = true)]
		public LOAITOUR LOAITOUR2
		{
			get
			{
				return this._LOAITOUR2.Entity;
			}
			set
			{
				LOAITOUR previousValue = this._LOAITOUR2.Entity;
				if (((previousValue != value)
							|| (this._LOAITOUR2.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._LOAITOUR2.Entity = null;
						previousValue.TOURDLs2.Remove(this);
					}
					this._LOAITOUR2.Entity = value;
					if ((value != null))
					{
						value.TOURDLs2.Add(this);
						this._MALOAITOUR = value.MALOAITOUR;
					}
					else
					{
						this._MALOAITOUR = default(long);
					}
					this.SendPropertyChanged("LOAITOUR2");
				}
			}
		}

		public event PropertyChangingEventHandler PropertyChanging;

		public event PropertyChangedEventHandler PropertyChanged;

		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}

		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}

		private void attach_CT_TOURs(CT_TOUR entity)
		{
			this.SendPropertyChanging();
			entity.TOURDL = this;
		}

		private void detach_CT_TOURs(CT_TOUR entity)
		{
			this.SendPropertyChanging();
			entity.TOURDL = null;
		}

		private void attach_CT_TOURs1(CT_TOUR entity)
		{
			this.SendPropertyChanging();
			entity.TOURDL1 = this;
		}

		private void detach_CT_TOURs1(CT_TOUR entity)
		{
			this.SendPropertyChanging();
			entity.TOURDL1 = null;
		}

		private void attach_CT_TOURs2(CT_TOUR entity)
		{
			this.SendPropertyChanging();
			entity.TOURDL2 = this;
		}

		private void detach_CT_TOURs2(CT_TOUR entity)
		{
			this.SendPropertyChanging();
			entity.TOURDL2 = null;
		}
	}
}
#pragma warning restore 1591
